# Generated by Django 5.2.10 on 2026-01-29 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seafarer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='성명')),
                ('rank', models.CharField(choices=[('CAPTAIN', '선장'), ('CHIEF_MATE', '1항사'), ('CHIEF_ENGINEER', '기관장'), ('ABLE_SEAMAN', '갑판수')], max_length=20, verbose_name='직책')),
                ('nationality', models.CharField(max_length=50, verbose_name='국적')),
            ],
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='선박명')),
                ('imo_number', models.CharField(max_length=20, unique=True, verbose_name='IMO 번호')),
                ('vessel_type', models.CharField(choices=[('CONTAINER', '컨테이너선'), ('BULK', '벌크선'), ('LNG', 'LNG선'), ('TANKER', '유조선')], max_length=20, verbose_name='선종')),
                ('built_year', models.IntegerField(verbose_name='건조년도')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='seafarer',
            name='vessel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crew', to='main.vessel', verbose_name='승선 선박'),
        ),
    ]
