# Generated by Django 5.2.10 on 2026-01-30 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_seafarer_vessel_delete_post_seafarer_vessel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seafarer',
            name='vessel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crew', to='main.vessel'),
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='장비명')),
                ('maker', models.CharField(blank=True, max_length=100, verbose_name='제조사')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='main.vessel')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200, verbose_name='작업명')),
                ('interval_days', models.IntegerField(verbose_name='정비 주기(일)')),
                ('last_performed', models.DateField(verbose_name='최근 정비일')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='main.equipment')),
            ],
        ),
    ]
