# Generated by Django 5.2.10 on 2026-01-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_seafarer_vessel_equipment_maintenancejob'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessel',
            name='latitude',
            field=models.FloatField(default=35.1),
        ),
        migrations.AddField(
            model_name='vessel',
            name='longitude',
            field=models.FloatField(default=129.04),
        ),
    ]
