# Generated by Django 5.2.10 on 2026-02-03 12:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_vessel_latitude_vessel_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='증서명')),
                ('expiry_date', models.DateField(verbose_name='만료일')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='main.vessel')),
            ],
        ),
        migrations.CreateModel(
            name='NoonReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(default=django.utils.timezone.now)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('sog', models.FloatField(verbose_name='평균 속도(Knot)')),
                ('distance', models.FloatField(verbose_name='운항 거리(NM)')),
                ('fuel_consumption', models.FloatField(verbose_name='연료 소모량(MT)')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noon_reports', to='main.vessel')),
            ],
        ),
        migrations.CreateModel(
            name='WorkRestHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('work_hours', models.FloatField(verbose_name='총 근로 시간')),
                ('seafarer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_hours', to='main.seafarer')),
            ],
        ),
    ]
